# Generated by Django 4.0.4 on 2022-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articles_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
