# Generated by Django 4.0.4 on 2022-04-13 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_alter_articles_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(related_name='article_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
