# Generated by Django 4.0.4 on 2022-04-15 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0010_articles_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='block_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
